### ISSUE TITLE
2024S2 Update appears to have broken the integration

### ISSUE THREAD

**Issue by deanacollins** [cazeaux/ha-iracing#10]
I could be wrong and it might just be something up with my configuration, but the latest iRacing updates appear to have stopped the integration working.  I haven't had anything pull since last tuesday when the new patch was released.

**Comment by cazeaux** [comment]
The integration is still working, but a change is required due to the licence split.
I did not yet have a chance to working it ... but on it today.

**Comment by cazeaux** [comment]
Fixed by #11, published in v1.2.0
