### ISSUE TITLE
API Limit

### ISSUE THREAD

**Issue by hylas1** [cazeaux/ha-iracing#14]
I've been trying to add all my team mates to this integration so I can make some automations when someone gets a new win but when I start adding more people I find a lot of the sensors start dropping off. I'm assuming I'm hitting an API limit with all the constant calls going to iracing.

I've tried disabling a lot of the sensors that I'm not using but the sensor.driver_name_driver one does have a lot of attributes associated to it. Maybe that sensor could be trimmed to help as well? I don't know, I'm just guessing here.

This can be reproduced by just adding more iracing numbers to your list, get to like 10-15 users and you'll start to see some drop off.

**Comment by cazeaux** [comment]
This is surprising as the API limit is quite high : 240 requests per minute. For one driver, the integration needs at worst 5 requests and the refresh is done every 30 minutes.

Disabling sensors will not change anything, as it will not disable the requests to iracing. And there is not one request per sensor, but 3 requests per driver refresh (5 at worst when a login is required).

Can you get your logs to see what is displayed ?
Did you update to 1.2.0 (as the previous version was broken by the 24S2 update) ?

**Comment by cazeaux** [comment]
If you go to Settings > System > Logs, you should be able to grab something.
Can you also tell me wich sensors started to drop off ? If it is the sensors related to "road" this is normal as "road" licence has disappeared (replaced by formula_car and sports_car).

**Comment by hylas1** [comment]
![Screenshot from 2024-03-12 03-39-28](https://github.com/cazeaux/ha-iracing/assets/113316907/eaefca5a-e8db-41fa-84f7-7035f503184e)
![Screenshot from 2024-03-12 03-50-25](https://github.com/cazeaux/ha-iracing/assets/113316907/ccbcc4cb-9cdd-4272-b502-dc169f901627)

This was happening to all sensors, some users were still active but others had all of the sensors drop off. This was happening before the latest update to iracing.
I've added 21 users currently and then restarted HA, before the restart they were all showing as active (this might of changed if I had waited longer) but after the restart I now have 13 users with all sensors unavailable.

There isn't much in Settings > System > Logs, I've attached one log but there's not much info in it.

**Comment by hylas1** [comment]
![Screenshot from 2024-03-13 17-24-43](https://github.com/cazeaux/ha-iracing/assets/113316907/083f0f94-483c-4da2-a8c4-ea00b723082e)

I've noticed another error in the log after it's been running for a little while. Not sure if this helps but here it is anyway.

**Comment by cazeaux** [comment]
Thank you. I think that this is a consequence of the failed sensor initialization.
I may have an idea of what's going wrong. With many drivers, I think that it create a race conditions for the authentication to the API.
I will not be able to work on it before the week-end, but you can expect a tentative fix this week-end.

**Comment by hylas1** [comment]
No rush, I'll test it when it's ready. Thanks

**Comment by cazeaux** [comment]
Actually you were right, it was indeed a rate limit problem, but for the login request. I discovered that the login request has a specific rate limit, with a limit to 5 (but very short reset).
And due to the asynchronous processing of HA, all login requests for all drivers were sent simultaneously, thus not waiting for the first one to create the session for the next ones.

This should now work properly with **v1.2.1**, can you try ?
Good new is that it was easy to reproduce, and I could validate on my side that the fix is OK.

You might need to recreate the drivers (sorry 😑)

**Comment by hylas1** [comment]
Looks like it's working. All entities are staying active after patching, however I do get errors showing in my logs.

![Screenshot from 2024-03-17 03-24-10](https://github.com/cazeaux/ha-iracing/assets/113316907/75e806ce-8b58-42b1-96a4-f1f26d35b956)
![Screenshot from 2024-03-17 03-24-06](https://github.com/cazeaux/ha-iracing/assets/113316907/b0325b4c-7d4f-499c-b99d-aed3ac856d83)

**Comment by cazeaux** [comment]
Ok this is just a warning, it should not create any problem. But I will look into it.

**Comment by hylas1** [comment]
Thanks for this fix, this can be closed now unless you want it open for the time being to look into that warning. I'm going to test my automations now, I can share them if you want to see what I'm mainly using your integration for.

**Comment by cazeaux** [comment]
The v1.2.2 fixes the connection pool warning. Tell me if it works for you. I will close after your feedback to be sure.
I would be happy to see what automation you are doing, it can give some new ideas :)

**Comment by hylas1** [comment]
Ok that warning is gone, this can be closed. Thanks again!


Alright I'll just add this onto the bottom here, just my idea of making use of the data from this integration.

Make an automation for when the driver_name_sports_car_wins changes state.
![Screenshot from 2024-03-17 05-01-29](https://github.com/cazeaux/ha-iracing/assets/113316907/727c4666-4880-4148-9b3e-51373535ce79)

Add this into the "And if" section
![Screenshot from 2024-03-17 05-01-39](https://github.com/cazeaux/ha-iracing/assets/113316907/6680ef67-ab96-4005-92ec-1ffbf5f2ad46)

and this next part is what I have in the "Then do" section.
![Screenshot from 2024-03-17 05-02-41](https://github.com/cazeaux/ha-iracing/assets/113316907/886a393b-2af1-4cbe-9ede-b1dc90672e2b)

This final image is what the notification currently looks like from the discord bot.
![Screenshot from 2024-03-17 05-07-48](https://github.com/cazeaux/ha-iracing/assets/113316907/0035cf4e-e0fa-45de-ad07-026661a5cfe2)

**Comment by cazeaux** [comment]
Thanks
