### ISSUE TITLE
Laps led not recording correctly for multiclass

### ISSUE THREAD

**Issue by hylas1** [cazeaux/ha-iracing#17]
I don't know if this is something that you can fix but I've noticed when one of my team mates gets a win in a slower class, the recent result doesn't show any laps led. Only the overall leader gets those laps led recorded.

**Comment by cazeaux** [comment]
If I understand correctly, the problem concerns multi class races where only the leader of the faster class gets laps led count.
I will check more in depth, but I would not be surprised that only the overall leader gets the laps led count. Maybe there is another parameter in the API for slower class ... will check.

**Comment by hylas1** [comment]
Yeah that's right. If it's not an option for the slower classes to get that from the API then I guess there's not much that can be done.

**Comment by cazeaux** [comment]
So I have checked the available data, and I can confirm that I can't see any data giving the laps lead in class.
Nothing that I can do so ...
I close the issue.
