### ISSUE TITLE
Recent API changes

### ISSUE THREAD

**Issue by deanacollins** [cazeaux/ha-iracing#18]
Hi, I believe the recent iRacing API changes have broken the HA intergration, is this something that can be resolved?

**Comment by cazeaux** [comment]
Hello

There is a recent change in security settings in your iRacing account, where they have disabled by default the authentication used by the apps. You need to enable it.

I guess it will be better in some future, when they implement a proper oauth.

https://support.iracing.com/support/solutions/articles/31000173894-enabling-or-disabling-legacy-read-only-authentication

**Comment by deanacollins** [comment]
Brilliant, thank you very much.
