### ISSUE TITLE
Authentication not working

### ISSUE THREAD

**Issue by imsuperimposed** [cazeaux/ha-iracing#19]
Authentication no longer working after restarting my HA device, when entering credentials I get "invalid authentication" message, credentials work fine when I log into iRacing website.

**Comment by imsuperimposed** [comment]
> Authentication no longer working after restarting my HA device, when entering credentials I get "invalid authentication" message, credentials work fine when I log into iRacing website.

Ok fixed, looks like you now need to enable Legacy Authentication in iRacing account settings, in case anyone else has this issue.

**Comment by cazeaux** [comment]
It was already covered by a previous issue, and the information is at the start of the readme 😉

**Comment by imsuperimposed** [comment]
Yes, but I think iRacing have made changes recently, as this was turned off. And I had to re enable it as it stopped working.
